name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -ntp

    - name: Publish Jacoco report as artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jacoco-report
        path: target/site/jacoco

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: folio-app-backend
        path: target/flight-app-backend-*.jar